### ISSUE TITLE
AUTH0_DOMAIN, API_AUDIENCE, and ALGORITHMS are not defined (SOLVED)

### ISSUE THREAD

**Issue by berdal84** [futurepatterns/notes#2]
Running app gives an error related to Settings class:

```
(venv) berenger@berenger-iMac:~/futurepatterns/notes/backend$ uvicorn app.main:app --reload
INFO:     Will watch for changes in these directories: ['/home/berenger/futurepatterns/notes/backend']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [38763] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/berenger/.pyenv/versions/3.12.1/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/berenger/.pyenv/versions/3.12.1/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/berenger/futurepatterns/notes/backend/venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/berenger/futurepatterns/notes/backend/venv/lib/python3.12/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/berenger/.pyenv/versions/3.12.1/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/berenger/.pyenv/versions/3.12.1/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/berenger/.pyenv/versions/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/berenger/futurepatterns/notes/backend/venv/lib/python3.12/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/berenger/futurepatterns/notes/backend/venv/lib/python3.12/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/berenger/futurepatterns/notes/backend/venv/lib/python3.12/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/berenger/.pyenv/versions/3.12.1/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/berenger/futurepatterns/notes/backend/app/main.py", line 7, in <module>
    from app.api import v1
  File "/home/berenger/futurepatterns/notes/backend/app/api/v1/__init__.py", line 1, in <module>
    from .routes import router
  File "/home/berenger/futurepatterns/notes/backend/app/api/v1/routes.py", line 9, in <module>
    from app import deps, models, schemas
  File "/home/berenger/futurepatterns/notes/backend/app/deps/__init__.py", line 1, in <module>
    from .auth import authenticate
  File "/home/berenger/futurepatterns/notes/backend/app/deps/auth.py", line 11, in <module>
    from app.deps.misc import get_db
  File "/home/berenger/futurepatterns/notes/backend/app/deps/misc.py", line 1, in <module>
    from app.db.session import SessionLocal
  File "/home/berenger/futurepatterns/notes/backend/app/db/session.py", line 4, in <module>
    from app.config import settings
  File "/home/berenger/futurepatterns/notes/backend/app/config.py", line 59, in <module>
    settings = get_settings()
               ^^^^^^^^^^^^^^
  File "/home/berenger/futurepatterns/notes/backend/app/config.py", line 56, in get_settings
    return Settings()
           ^^^^^^^^^^
  File "/home/berenger/futurepatterns/notes/backend/venv/lib/python3.12/site-packages/pydantic/env_settings.py", line 40, in __init__
    super().__init__(
  File "/home/berenger/futurepatterns/notes/backend/venv/lib/python3.12/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 3 validation errors for Settings
AUTH0_DOMAIN
  field required (type=value_error.missing)
API_AUDIENCE
  field required (type=value_error.missing)
ALGORITHMS
  field required (type=value_error.missing)
```

I solved the issue by setting default values to those 3 fields. But cannot push a branch:

```
berenger@berenger-iMac:~/futurepatterns/notes/frontend$ git push -u origin fix/config-default-values 
ERROR: Permission to futurepatterns/notes.git denied to berdal84.
fatal: Impossible de lire le dépôt distant.

Veuillez vérifier que vous avez les droits d'accès
et que le dépôt existe.
```

**Comment by rjmello** [comment]
Nice catch; I've added these to `backend/README.md`.
